I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 533, in script
    jump Day_4
ScriptError: could not find label 'Day_4'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 533, in script
    jump Day_4
  File "C:\Users\jadal\Desktop\renpy-7.4.10-sdk/renpy/ast.py", line 1757, in execute
    rv = renpy.game.script.lookup(target)
  File "C:\Users\jadal\Desktop\renpy-7.4.10-sdk/renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'Day_4'.

Windows-10-10.0.19041
Ren'Py 7.4.10.2178
Insect Incest 1.0
Wed Nov 24 18:50:44 2021
